name: usw_chat_bot_app
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  velocity_x: ^4.1.2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.3
  change_app_package_name: ^1.1.0
  animations: ^2.0.11
  logger: ^2.3.0
  http: ^1.2.1
  stomp_dart_client: ^0.4.4
  web_socket_channel: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/usw_logo.png
    - assets/images/android_light_sq_SU@1x.png
    - assets/images/kakao_login_medium_narrow.png
