// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSzYCtq6ArGZkfbIxKZSDtp5iE02qoAmA',
    appId: '1:359602925923:web:65bbaf8fe8c97a2d8f2356',
    messagingSenderId: '359602925923',
    projectId: 'usw-chat-bot-app',
    authDomain: 'usw-chat-bot-app.firebaseapp.com',
    storageBucket: 'usw-chat-bot-app.appspot.com',
    measurementId: 'G-BBYFE65YYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCbuEC9iqAdNJrlunyNb7D4rokKixXfu8',
    appId: '1:359602925923:android:5a98daf814f09bc28f2356',
    messagingSenderId: '359602925923',
    projectId: 'usw-chat-bot-app',
    storageBucket: 'usw-chat-bot-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSzYCtq6ArGZkfbIxKZSDtp5iE02qoAmA',
    appId: '1:359602925923:web:50dd19748b2d577a8f2356',
    messagingSenderId: '359602925923',
    projectId: 'usw-chat-bot-app',
    authDomain: 'usw-chat-bot-app.firebaseapp.com',
    storageBucket: 'usw-chat-bot-app.appspot.com',
    measurementId: 'G-SK99BJFLTV',
  );
}
